name: verbeelding_verbindt
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  bot_toast: ^4.0.1
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.5
  cloud_functions: ^1.0.3
  dartz: ^0.10.0-nullsafety.1
  device_info: ^2.0.0
  dio: ^4.0.0
  equatable: ^2.0.0
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  flutter_bloc: ^7.0.0
  flutter_spinkit: ^5.0.0
  geolocator: ^7.0.3
  get_it: ^6.1.1
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  package_info: ^2.0.0
  permission_handler: ^7.1.0
  platform_device_id: ^1.0.1
  pretty_dio_logger: ^1.1.1
  qr_code_scanner: ^0.4.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner: ^2.0.1
  effective_dart: ^1.3.1
  json_serializable: ^4.0.3
  mocktail: ^0.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/intro-header.jpg
    - assets/images/unknown-artist.jpg
