name: verbeelding_verbindt
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  verbeelding_verbindt_core:
    path: verbeelding_verbindt_core
  verbeelding_verbindt_data_route_xl:
    path: verbeelding_verbindt_data_route_xl
  verbeelding_verbindt_data_firebase:
    path: verbeelding_verbindt_data_firebase
  verbeelding_verbindt_data_shared_preferences:
    path: verbeelding_verbindt_data_shared_preferences
  verbeelding_verbindt_ui:
    path: verbeelding_verbindt_ui

  equatable: ^2.0.0
  firebase_core: ^1.0.0
  firebase_crashlytics: ^2.0.0
  get_it: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true