name: verbeelding_verbindt_data_shared_preferences
publish_to: none

environment:
  sdk: ">=2.14.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  get_it: ^7.0.0
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.11
  rx_shared_preferences: ^2.3.0
  verbeelding_verbindt_core:
    path: ../verbeelding_verbindt_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
