name: verbeelding_verbindt_presentation
description: A new Flutter package project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  bitmap: ^0.1.2
  blurhash_dart: ^1.0.2
  bot_toast: ^4.0.1
  cached_network_image: ^3.0.0
  entry: ^0.0.2+2
  equatable: ^2.0.0
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.17.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.1
  flutter_spinkit: ^5.0.0
  freezed: ^0.14.1
  freezed_annotation: ^0.14.1
  get_it: ^7.1.3
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  photo_view: ^0.11.1
  qr_code_scanner: ^0.4.0
  rxdart: ^0.27.0
  supercharged: ^2.0.0
  url_launcher: ^6.0.3
  video_player: ^2.1.1
  verbeelding_verbindt_core:
    path: ../core

dev_dependencies:
  bloc_test: ^8.0.0
  build_runner: ^1.10.3
  flutter_lints: ^1.0.4
  flutter_gen_runner: ^3.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.3
  mocktail: ^0.1.0

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  # generate: true
  assets:
   - assets/images/intro-header.jpg
   - assets/images/unknown-artist.jpg