targets:
  $default:
    builders:
      json_serializable|json_serializable:
        generate_for:
          - "**/models/**.dart"
          - "**/entities/**.dart"
        options:
          explicit_to_json: true
          include_if_null: false
      freezed|freezed:
        generate_for:
          - "**/models/**.dart"
          - "**/entities/**.dart"
          - "**/bloc/**.dart"