name: verbeelding_verbindt_ui
description: A new Flutter package project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  verbeelding_verbindt_core:
    path: ../../shared/core

  bitmap: ^0.1.0
  blurhash_dart: ^1.0.0
  cached_network_image: ^3.0.0
  device_info: ^2.0.0
  entry: ^0.0.0
  equatable: ^2.0.0
  firebase_core: ^1.0.0
  firebase_crashlytics: ^2.0.0
  flutter_bloc: ^8.0.0
  flutter_hooks: ^0.18.0 
  flutter_markdown: ^0.6.0
  flutter_spinkit: ^5.0.0
  flutter_wizard: ^2.0.3
  freezed_annotation: ^1.0.0
  geolocator: ^8.0.0
  get_it: ^7.0.0
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.0
  go_router: ^2.5.5
  intl: ^0.17.0
  json_annotation: ^4.4.0
  konami_detector: ^1.0.0
  package_info: ^2.0.0
  photo_view: ^0.13.0
  qr_code_scanner: ^0.6.1
  rxdart: ^0.27.0
  tuple: ^2.0.0
  url_launcher: ^6.0.0
  video_player: ^2.0.0
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.0
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  freezed: ^1.0.0
  json_serializable: ^6.1.3
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/intro-header.jpg
   - assets/images/unknown-artist.jpg