include: ../analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false

exclude:
  - "**/*.g.dart"
  - "**/*.freezed.dart"

errors:
  invalid_annotation_target: ignore