name: verbeelding_verbindt_core
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.0
  collection: ^1.15.0
  dartz: ^0.10.0
  equatable: ^2.0.0
  firebase_core: ^1.0.0
  firebase_crashlytics: ^2.0.0
  freezed_annotation: ^1.0.0
  get_it: ^7.0.0
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.0
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  freezed: ^1.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  generate: true