name: verbeelding_verbindt_data
description: A new Flutter package project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  equatable: ^2.0.0
  get_it: ^7.0.0
  cloud_firestore: ^3.0.0
  cloud_functions: ^3.0.0
  firebase_auth: ^3.0.0
  firebase_core: ^1.0.0
  firebase_crashlytics: ^2.0.0
  geolocator: ^7.0.0
  json_annotation: ^4.0.0
  permission_handler: ^8.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.0
  verbeelding_verbindt_core:
    path: ../verbeelding_verbindt_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true