name: verbeelding_verbindt_data_route_xl
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  get_it: ^7.0.0
  json_annotation: ^4.3.0
  verbeelding_verbindt_core:
    path: ../verbeelding_verbindt_core
  verbeelding_verbindt_data:
    path: ../verbeelding_verbindt_data
  verbeelding_verbindt_data_http:
    path: ../verbeelding_verbindt_data_http

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
