
name: CI PROD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: 
      - master
    tags:
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job configuration for the Flutter State Challenge App
  format:
    name: Format, Analyze & Test

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Ensure correct JAVA version is installed.
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Download all Flutter packages the Flutter State Challenge App depends on
      - name: Download dependencies
        run: .github/flutter_pub_get.sh
     
      # Run Flutter Analyzer
      - name: Run Flutter Analyzer
        run: .github/flutter_analyze.sh
      
      # Run all unit-tests with code coverage
      - name: Run unit tests
        run: .github/flutter_test.sh
        
  build_android:
    name: Build Android App
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Ensure correct JAVA version is installed.
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Download all Flutter packages the Flutter State Challenge App depends on
      - name: Download dependencies
        run: .github/flutter_pub_get.sh

      # Generate files by running build runnder
      - name: Generate files
        run: .github/flutter_pub_build_runner.sh

      # Build Android version of the Flutter State Management App
      - name: Run Android build
        run: .github/flutter_build_android.sh -t lib/main_production.dart -f production
        
  build_ios:
    name: Build iOS App
    
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Ensure correct JAVA version is installed.
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Download all Flutter packages the Flutter State Challenge App depends on
      - name: Download dependencies
        run: .github/flutter_pub_get.sh

      # Generate files by running build runnder
      - name: Generate files
        run: .github/flutter_pub_build_runner.sh

      # Build iOS version of the Flutter State Management App
      - name: Run iOS build
        run: .github/flutter_build_ios.sh -t lib/main_production.dart -f production
