name: verbeelding_verbindt

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Install Dependencies
        run: .github/flutter_pub_get.sh

      # - name: Format
      #   run: .github/flutter_format.sh

      - name: Analyze
        run: .github/flutter_analyze.sh

      # - name: Run tests
      #   run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      # - name: Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
